version: "3"
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: defilev
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: defi
    volumes:
      - pg-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pg-data:
    driver: local
